// src/lib/components/Name.svelte
<section id="name">
  <span id="first-name">Sascha</span>
  <span id="last-name">Münchow</span>
  <hr />
  <span id="title">Frontend Evangelist</span>
</section>

<style>
  #name {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  #first-name {
    font-weight: 700;
    text-transform: uppercase;
    font-size: 3.5rem;
  }

  #last-name {
    text-transform: uppercase;
    font-size: 2.5rem;
    margin-top: -0.65em;
  }

  hr {
    width: 100%;
    border: 1px solid currentColor;
    margin-top: -0.4em;
  }

  #title {
    font-weight: 300;
    font-size: 1.55rem;
    margin-top: -0.4em;
  }
</style>

// app/components/sidebar/Name.vue
<template>
  <section id="name">
    <span id="first-name">Sascha</span>
    <span id="last-name">Münchow</span>
    <hr />
    <span id="title">Frontend Evangelist</span>
  </section>
</template>

<style scoped>
#name {
  display: flex;
  flex-direction: column;
  align-items: center;
}

#first-name {
  font-weight: 700;
  text-transform: uppercase;
  font-size: 3.5rem;
}

#last-name {
  text-transform: uppercase;
  font-size: 2.5rem;
  margin-top: -0.65em;
}

hr {
  width: 100%;
  border: 1px solid currentColor;
  margin-top: -0.4em;
}

#title {
  font-weight: 300;
  font-size: 1.55rem;
  margin-top: -0.4em;
}
</style>
