// src/routes/conferences/+page.svelte
<ul>
  <li>Vue.js Amsterdam 2022 & JSWorld Conference 2022 1 - 3 Juni</li>
  <li>Nuxt Nation 2022 16 & 17 November</li>
  <li>Vue.js Nation 2023 25 & 26 Januar</li>
  <li>ViteConf 2023 5 & 6 Oktober</li>
  <li>Nuxt Nation 2023 18 & 19 Oktober</li>
  <li>Vue.js Nation 2024 24 & 25 Januar</li>
  <li>Frontend Nation 2024 4 - 7 Juni</li>
  <li>ViteConf 2024 3 & 4 Oktober</li>
  <li>CypressConf 2024 22 & 23 Oktober</li>
  <li>Nuxt Nation 2024 12 & 13 November</li>
</ul>

<script lang="ts">
  import type { PageData } from './$types';

  export let data: PageData;
</script>

// app/pages/conferences.vue
<template>
  <h1>Comming soon...</h1>
</template>

<script setup lang="ts">
// Vue.js Amsterdam 2022 & JSWorld Conference 2022	1 - 3 Juni
// Nuxt Nation 2022		16 & 17 November
// Vue.js Nation 2023		25 & 26 Januar
// ViteConf 2023			5 & 6 Oktober
// Nuxt Nation 2023		18 & 19 Oktober
// Vue.js Nation 2024		24 & 25 Januar
// Frontend Nation 2024	4 - 7 Juni
// ViteConf 2024			3 & 4 Oktober
// CypressConf 2024		22 & 23 Oktober
// Nuxt Nation 2024		12 & 13 November
</script>

<style scoped>
/* ToDo: Add style content */
</style>
