// src/routes/profile/+page.svelte
<Block header="Kurzprofil">
  <p>
    Technologie liegt mir im Blut. Schon 2004 machte ich meine ersten Versuche mit HTML, CSS und
    Flash, bevor ich mich entschied, mehr über die Grundlagen der Gestaltung in einer Ausbildung zum
    Mediengestalter zu lernen. Doch selbst als ich in einigen Druckereien arbeitete, haben mich
    Webtechnologien nie wirklich losgelassen und ich entschied mich 2012 dazu, Informatik zu
    studieren, um nicht nur Webdesign, sondern auch Webentwicklung zu lernen.
  </p>
  <p>
    Nach meinem Studium hatte ich das Glück, viele neue Technologien kennen zulernen und mir in der
    novomind AG einen Ruf als Frontend Experten zu erarbeiten. Nachdem ich über jQuery und
    Angular.js schlussendlich bei Vue.js landete, bekam ich die Aufgabe als Frontend Architect im
    Internationalen Core-Team den Aufbau einer neuen Administrationsoberfläche für unser Shopsystem
    zu leiten.
  </p>
  <p>
    Nun bin ich auf der Suche nach neuen Herausforderungen, um meinen Wissensdurst und meine Liebe
    fürs Frontend zu stillen. Ich liebe es, lösungsorientiert zu arbeiten und kreative und elegante
    Lösungen für komplexe Probleme zu finden.
  </p>
</Block>
<Block header="Kontakt">
  <Contact />
</Block>

<script lang="ts">
  import Block from '$lib/components/Block.svelte';
  import Contact from '$lib/components/Contact.svelte';
</script>

// app/pages/profile.vue
<template>
  <div>
    <UiBlock header="Kurzprofil">
      <p>
        Technologie liegt mir im Blut. Schon 2004 machte ich meine ersten Versuche mit HTML, CSS und
        Flash, bevor ich mich entschied, mehr über die Grundlagen der Gestaltung in einer Ausbildung
        zum Mediengestalter zu lernen. Doch selbst als ich in einigen Druckereien arbeitete, haben
        mich Webtechnologien nie wirklich losgelassen und ich entschied mich 2012 dazu, Informatik
        zu studieren, um nicht nur Webdesign, sondern auch Webentwicklung zu lernen.
      </p>
      <p>
        Nach meinem Studium hatte ich das Glück, viele neue Technologien kennen zulernen und mir in
        der novomind AG einen Ruf als Frontend Experten zu erarbeiten. Nachdem ich über jQuery und
        Angular.js schlussendlich bei Vue.js landete, bekam ich die Aufgabe als Frontend Architect
        im Internationalen Core-Team den Aufbau einer neuen Administrationsoberfläche für unser
        Shopsystem zu leiten.
      </p>
      <p>
        Nun bin ich auf der Suche nach neuen Herausforderungen, um meinen Wissensdurst und meine
        Liebe fürs Frontend zu stillen. Ich liebe es, lösungsorientiert zu arbeiten und kreative und
        elegante Lösungen für komplexe Probleme zu finden.
      </p>
    </UiBlock>
    <UiBlock header="Kontakt">
      <Contact />
    </UiBlock>
  </div>
</template>
