// src/lib/components/TimedEvents.svelte
<div class="events">
  {#each events as event, index (index)}
    <TimedEvent {event} />
  {/each}
</div>

<style>
  .events {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    overflow-y: auto;
    max-height: var(--block-content-height);
  }
</style>

<script lang="ts">
  import type { TimedEventEntry } from '$lib/types';
  import TimedEvent from '$lib/components/TimedEvent.svelte';

  export let events: TimedEventEntry[];
</script>

// app/components/ui/TimedEvents.vue
<template>
  <div class="events">
    <UiTimedEvent v-for="(event, index) of events" :key="index" :event="event" />
  </div>
</template>

<script setup lang="ts">
import type { TimedEventEntry } from '~/types/types';

type Props = {
  events: TimedEventEntry[];
};

defineProps<Props>();
</script>

<style scoped>
.events {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  overflow-y: auto;
  max-height: var(--block-content-height);
}
</style>
